### PR TITLE
 Wk4 modifications

### PR DESCRIPTION
**Pull request by sylvainschmitt**
# **Don't accept the pull request yet**. 

This is some quick suggestions of rendering but not change of content yet. All changes are in NEWS.  This concerns only the beginning of the document (until the `r knitr::opts_chunk$set(eval = F)`). This only a pull request to discuss modification. I may continue after lunch but I wanted to share first modifications. I attached the html compiled: [Workshop4_HierarchicalModels.html.zip](https://github.com/JulietteArchambeau/BiogecoBayes/files/4444104/Workshop4_HierarchicalModels.html.zip).

.

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
\beta_{age2}age^{2}_{i} are missing in the normal model in stan

**Comment by sylvainschmitt** [comment]
You made two times the same model in lognormal fixed effects, I'm just removing one for the moment

**Comment by sylvainschmitt** [comment]
I pushed a new version with updated section 3.1 One varying intercept. I added lognormal model with lognormal priors in fixed effects models. And I added lognormal non-centered parametrisation in one varying intercept models. See the html in attachment [Workshop4_HierarchicalModels.html.zip](https://github.com/JulietteArchambeau/BiogecoBayes/files/4445655/Workshop4_HierarchicalModels.html.zip)
. I'll stop playing with the document before the skype. But the lognormal non-centered parameterisation fixed the divergence (even if we can still improve the model).

**Comment by JulietteArchambeau** [comment]
Comments about the new modifs:
* I rearranged the models of the 'fixed effects' and 'one-varying intercept' parts. 
* The models now have more informative names (the old models start with "mod" and can be deleted when we have corrected the whole document, so not yet)!
* In the "Fixed effects" part , the lognormal defined on R+ has a lower fit than lognormal define on R (maybe something wrong with the lognormal models yet, you should Sylvain!)
* Why do the parameters have so strong correlation in the one-varying intercept normal models with log(y) (mmlogyC and mmNlogyNC)??

**Comment by JulietteArchambeau** [comment]
And here the html! 
[Workshop4_HierarchicalModels.html.zip](https://github.com/JulietteArchambeau/BiogecoBayes/files/4453149/Workshop4_HierarchicalModels.html.zip)

**Comment by sylvainschmitt** [comment]
> In the "Fixed effects" part , the lognormal defined on R+ has a lower fit than lognormal define on R (maybe something wrong with the lognormal models yet, you should Sylvain!)

Yep you made  a mixed up of lognormal parmaeterisation because for mLogNR you used y ~ logN(mu, sigma) whereas for mLogNR you used y ~ logN(log(mu), sigma) .

**Comment by JulietteArchambeau** [comment]
In mLogNRplus, I used y ~ logN(log(mu), sigma) and in mLogNR, I used y ~ logN(mu, sigma). I thought that's what you advised me to do, but I probably didn't understand. I thought that mLogNRplus should be better than mLogNR, but it's the opposite. Feel free to correct the stancode because I don't understand what I'm supposed to change :/

**Comment by sylvainschmitt** [comment]
If you write Y ~ logN(mu, sigma) you have parameter on the latent scale (the logged one) as when you do log(Y) ~ N(mu, sigma) whereas when you write Y ~ logN(log(mu), sigma) you have parameters on the data scale as when you do Y ~ N(mu, sigma). So when you write Y ~ logN(mu, sigma) you are already on R+. So I say we keep it that way and delete the second log model (too much explanation) as lognormal distribution aren't the focus of this session.

**Comment by sylvainschmitt** [comment]
You were unfair with vectorized model 2 as mu was still in a loop !

**Comment by sylvainschmitt** [comment]
I pushed my changes, but I'm still compiling the document. You can still push back your version. I removed the lognormal on R+ and kept your first version as it is just an example and not a presentation on the lognormal distribution (but this is a suggestion), and I removed lognormal from prior test though. I also merged titles with model subtitles. I find the document start to be really clear and great !

**Comment by sylvainschmitt** [comment]
The resulting html: [Workshop4_HierarchicalModels.html.zip](https://github.com/JulietteArchambeau/BiogecoBayes/files/4455702/Workshop4_HierarchicalModels.html.zip)

**Comment by sylvainschmitt** [comment]
And by the way for non-centered random effects in stan you can use a more efficient implementation of the standard normal N(0,1): `std_normal()` instead of `normal(0,1)`.

**Comment by JulietteArchambeau** [comment]
Great! Thanks for the changes! 

> "And by the way for non-centered random effects in stan you can use a more efficient implementation of the standard normal N(0,1): std_normal() instead of normal(0,1)."

Oh, good to know! I will add it as a comment in the code :)

> ". I removed the lognormal on R+ and kept your first version as it is just an example and not a presentation on the lognormal distribution (but this is a suggestion), and I removed lognormal from prior test though."

Ok you're right, it's not the focus. But I would love to understand more this distribution, maybe it could be the topic of another workshop? 

> "You were unfair with vectorized model 2 as mu was still in a loop !"

Aaah yes, good point X)

> "I find the document starts to be really clear and great !"

I agree!! Thanks a lot! I think that on Monday, we can present these two parts ("Fixed effects" and "One-varying intercept"). If it's ok with you, I won't touch the model codes anymore, I'll just add some text to make the workshop more narrative. 


That's it, you're done modifying it? and I can "pull" it again and finish some minor changes (for example I saw that the scatter plots of parameters don't always include the same parameters, so it's not easy to compare at first glance)?

**Comment by sylvainschmitt** [comment]
> That's it, you're done modifying it? and I can "pull" it again 

Yes.

> and finish some minor changes (for example I saw that the scatter plots of parameters don't always include the same parameters, so it's not easy to compare at first glance)?

Yep if you can have everything consistent between models it would be great.

> Ok you're right, it's not the focus. But I would love to understand more this distribution, maybe it could be the topic of another workshop?

Part of the explanation was on a previous comment:

> If you write Y ~ logN(mu, sigma) you have parameter on the latent scale (the logged one) as when you do log(Y) ~ N(mu, sigma) whereas when you write Y ~ logN(log(mu), sigma) you have parameters on the data scale as when you do Y ~ N(mu, sigma). So when you write Y ~ logN(mu, sigma) you are already on R+.

**Comment by JulietteArchambeau** [comment]
>" Yep if you can have everything consistent between models it would be great."

Ok, I will check that :) 

> "Part of the explanation was on a previous comment:"

Yes I read it, but I don't see in this case by a Lognormal defined on R...  (but anyway, I probably need to think more about it and read THE wikipedia page of the Lognormal ;)

**Comment by JulietteArchambeau** [comment]
Okay, I'm done with the changes, I think we can keep it like that for Monday!  And maybe put this branch back on the master branch? So that others can access it easily :)
Here is the new html version: 
[Workshop4_HierarchicalModels.html.zip](https://github.com/JulietteArchambeau/BiogecoBayes/files/4458863/Workshop4_HierarchicalModels.html.zip)

The lognormal NC had 16 divergent transitions and low effective sample size in my last compilation, if you want to have a last look. But I think it's already very good like that, we can stop there :) Well done!

**Comment by sylvainschmitt** [comment]
> Okay, I'm done with the changes, I think we can keep it like that for Monday! And maybe put this branch back on the master branch? So that others can access it easily :)
Here is the new html version:
Workshop4_HierarchicalModels.html.zip

On it !

> The lognormal NC had 16 divergent transitions and low effective sample size in my last compilation, if you want to have a last look. But I think it's already very good like that, we can stop there :) Well done!

Yes it's because of the definiton of the lognormal on log(mu), I think we haven't ensured the positiveness of mu.

**Comment by sylvainschmitt** [comment]
I did the merge of the branch on the master and thus deleted the branch (but thanks to git it can always be reopened !). But could you ensure than the html in the doc/ folder is updated ?

**Pull request merged**
